jobs:
  lint-build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install flake8
        run: pip install flake8

      - name: Lint code
        run: flake8 app.py

      - name: Build Docker image
        run: docker build -t face-detection-app .

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker tag face-detection-app ${{ secrets.DOCKERHUB_USERNAME }}/face-detection-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/face-detection-app:latest

      - name: Deploy on EC2 via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/face-detection-app:latest
            docker stop face-detection-container || true
            docker rm face-detection-container || true
            docker run -d --name face-detection-container ${{ secrets.DOCKERHUB_USERNAME }}/face-detection-app:latest
