name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install flake8
        run: pip install flake8

      - name: Lint code
        run: flake8 main.py

      - name: Build Docker image
        run: docker build -t face-detection-app .

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: docker tag face-detection-app ${{ secrets.DOCKERHUB_USERNAME }}/face-detection-app:latest && docker push ${{ secrets.DOCKERHUB_USERNAME }}/face-detection-app:latest
